services:
  app:
    restart: always
    image: eclaim-frontend:latest
    container_name: eclaim-frontend
    build:
      context: ./
      dockerfile: dockerfile.app
      args:
        NEXTAUTH_URL: http://10.25.68.72/claim
        NEXTAUTH_SERVER_URL: http://localhost:3000
        NEXT_PUBLIC_BACKEND_SERVER_URL: http://172.28.5.6:5000
        NEXT_PUBLIC_BACKEND_URL: http://10.25.68.72/claimback
    networks:
      project_network:
        ipv4_address: 172.28.5.5
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_SERVER_URL=http://172.28.5.6:5000
      - NEXT_PUBLIC_BACKEND_URL=http://10.25.68.72/claimback
      - NEXTAUTH_URL=http://10.25.68.72/claim
      - NEXTAUTH_SERVER_URL=http://localhost:3000
    env_file:
      - .env
    expose:
      - "3000"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"

networks:
  project_network:
    external: true
  proxy_network:
    external: true
      
        